### ISSUE TITLE
Problem with Request/Response with revoked certificate

### ISSUE THREAD

**Issue by JiriSch** [mlocati/ocsp#1]
Hello,

thank you for this library.
I have a problem with certificate which is revoked (others works well), but it shows a error in decoding result.

Decoded URL OCSP: http://ocsp.ica.cz/2qca16_rsa - it's OK

Tested with https://decoder.link/ocsp - shows rights values.
But doesnt work with this library, could you please look?

Thank you

-----BEGIN CERTIFICATE-----
MIIHwzCCBaugAwIBAgIEALDhPjANBgkqhkiG9w0BAQsFADB/MQswCQYDVQQGEwJD
WjEoMCYGA1UEAwwfSS5DQSBRdWFsaWZpZWQgMiBDQS9SU0EgMDIvMjAxNjEtMCsG
A1UECgwkUHJ2bsOtIGNlcnRpZmlrYcSNbsOtIGF1dG9yaXRhLCBhLnMuMRcwFQYD
VQQFEw5OVFJDWi0yNjQzOTM5NTAeFw0xOTEwMTgwODA0NDFaFw0yMDEwMTcwODA0
NDFaMFwxHzAdBgNVBAMMFkRyLiBIb3LDoWsgLSBQU0VVRE9OWU0xCzAJBgNVBAYT
AkNaMRMwEQYDVQRBDApEci4gSG9yw6FrMRcwFQYDVQQFEw5JQ0EgLSAxMDUxODk0
OTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJLjskYPvIJuLCA2GvE9
NWPpl1g52MoyYOgZD8SJBEcOvUdxlgxLtuMmaPxW/TeIc7ZI1QLVF6QDAIZ+jG9k
KwQ02okKfpgJCW4+LKdijZdbIg2SFu5Ph5HtXPbteBYwg91m8PsDl6vHKP6YTrO5
d5R3z7LjB+OQ79ww1A2OACk4usckfASRsSqmG94hZsYgOb+4l0U7bGP6LoRO2nwl
ieUuio3E/U0B6gMcUqN5A3NpJwxg2SvOqgS6qkzw21RDqHlVnEMM7qt+kqhjBvsq
ORXbvqCb+SVAf0KOHEjca7amNLIc5RO3jA8jb9yQfjjf6kf2Ro6rWVJb+fVlpXdK
LfUCAwEAAaOCA2gwggNkMDgGA1UdEQQxMC+BE3N0cmFuc2t5QGRpZ25pdGEuY3qg
GAYKKwYBBAGBuEgEBqAKDAgxMDUxODk0OTAOBgNVHQ8BAf8EBAMCBsAwCQYDVR0T
BAIwADCCASgGA1UdIASCAR8wggEbMIIBDAYNKwYBBAGBuEgKAR4BATCB+jAdBggr
BgEFBQcCARYRaHR0cDovL3d3dy5pY2EuY3owgdgGCCsGAQUFBwICMIHLGoHIVGVu
dG8ga3ZhbGlmaWtvdmFueSBjZXJ0aWZpa2F0IHBybyBlbGVrdHJvbmlja3kgcG9k
cGlzIGJ5bCB2eWRhbiB2IHNvdWxhZHUgcyBuYXJpemVuaW0gRVUgYy4gOTEwLzIw
MTQuVGhpcyBpcyBhIHF1YWxpZmllZCBjZXJ0aWZpY2F0ZSBmb3IgZWxlY3Ryb25p
YyBzaWduYXR1cmUgYWNjb3JkaW5nIHRvIFJlZ3VsYXRpb24gKEVVKSBObyA5MTAv
MjAxNC4wCQYHBACL7EABAjCBjwYDVR0fBIGHMIGEMCqgKKAmhiRodHRwOi8vcWNy
bGRwMS5pY2EuY3ovMnFjYTE2X3JzYS5jcmwwKqAooCaGJGh0dHA6Ly9xY3JsZHAy
LmljYS5jei8ycWNhMTZfcnNhLmNybDAqoCigJoYkaHR0cDovL3FjcmxkcDMuaWNh
LmN6LzJxY2ExNl9yc2EuY3JsMIGSBggrBgEFBQcBAwSBhTCBgjAIBgYEAI5GAQEw
CAYGBACORgEEMFcGBgQAjkYBBTBNMC0WJ2h0dHBzOi8vd3d3LmljYS5jei9acHJh
dnktcHJvLXV6aXZhdGVsZRMCY3MwHBYWaHR0cHM6Ly93d3cuaWNhLmN6L1BEUxMC
ZW4wEwYGBACORgEGMAkGBwQAjkYBBgEwZQYIKwYBBQUHAQEEWTBXMCoGCCsGAQUF
BzAChh5odHRwOi8vcS5pY2EuY3ovMnFjYTE2X3JzYS5jZXIwKQYIKwYBBQUHMAGG
HWh0dHA6Ly9vY3NwLmljYS5jei8ycWNhMTZfcnNhMB8GA1UdIwQYMBaAFHSCCJHj
2WRocYXW6zHkct+LJrFtMB0GA1UdDgQWBBTc33o5dlPVXLh0+YUNLu99OsdJATAT
BgNVHSUEDDAKBggrBgEFBQcDBDANBgkqhkiG9w0BAQsFAAOCAgEATbOjgEwdohCA
qyqdsG9F8X5xDDoMTqsN3D/p/OR1kDzBcFyQ4v0LmkgrPVn1oWSIxuvinLE2E/E6
iByqJNqni865wWCTt4kZtWCQlQwqPlUG+bvCjY3PlouU+Z0qVKebZ9vtAQNXyp1e
CH1Zjd0ik724KvAWU8ZvaCReDQO7ACLuyZpJnF/xL1cmS+bRkXUw50Hn2YvEHit6
aiPTDFoMWAFGSUQnKm/eksc+e/i7tg5mpRCc2aFAlDcTsLfpeuayBkzEijYKzSUp
5zMitBH5hG/uOQZO1SjxJnzHIyIiXsqO+1wercXYM9bYcDRkw+L7CtSiUlC1OtRa
1yKN7y7F5XJd29MJgfu5DgQ4RAIFcGwItUVc2HBjpmNxdu9Xf5wC12zRkGeEnsPD
FKPpbHUjBZZYNs2nbtYqyk4jo2ORhb3KqXpIpDtl5Ok7oeLMBY650DHxiCDNBgpt
1QaVbS31g/ZycpA0w5ELmdtBdAsOdgmvdMexKFPzvt/MBrXxu2BsdPA0CGWMOq3K
TZEsESf+G4FDLzzFNz5DbCRBP55sR2G+hvvXhPU2BPYI9Ir3vgnE9w/Fxxqp6xGG
GIKlRALSletgwQod8ktwZEhfyO8OqFt6opMN8qSMHv0HRHvlYyz/3kq83/lXklT6
OBgnA/Xji2TzgGS+7477ep2pycy3wmI=
-----END CERTIFICATE-----

**Comment by JiriSch** [comment]
Exactly the problem is:

[message:protected] => Call to undefined method Ocsp\Asn1\Element\RawConstructed::getValue()
  | [string:Error:private] =>
  | [code:protected] => 0
  | [file:protected] => ...vendor\mlocati\ocsp\src\Ocsp.php
  | [line:protected] => 304

**Comment by mlocati** [comment]
#2 should fix it

**Comment by mlocati** [comment]
I just released a new version: could you try to update your OCSP version and see if it's fixed now?

**Comment by JiriSch** [comment]
Thank you for new version, It moves somewhere else, don't know if I missed somethink, but I get:
`

>Ocsp\Exception\ResponseException\UnauthorizedException Object
--
  | (
  | [message:protected] => Request unauthorized
  | [string:Exception:private] =>
  | [code:protected] => 0
  | [file:protected] => C:\podatelna\_components\php7\vendor\mlocati\ocsp\src\Exception\ResponseException\UnauthorizedException.php
  | [line:protected] => 19
  | [trace:Exception:private] => Array
  | (
  | [0] => Array
  | (
  | [file] => C:\podatelna\_components\php7\vendor\mlocati\ocsp\src\Ocsp.php
  | [line] => 197
  | [function] => create
  | [class] => Ocsp\Exception\ResponseException\UnauthorizedException
  | [type] => ::
  | [args] => Array
  | (
  | )
  |  
  | )
  |  
  | [1] => Array
  | (
  | [file] => C:\podatelna\_components\php7\vendor\mlocati\ocsp\src\Ocsp.php
  | [line] => 160
  | [function] => checkResponseStatus
  | [class] => Ocsp\Ocsp
  | [type] => ->
  | [args] => Array
  | (
  | [0] => Ocsp\Asn1\Element\Sequence Object
  | (
  | [elements:Ocsp\Asn1\Element\AbstractList:private] => Array
  | (
  | [0] => Ocsp\Asn1\Element\RawPrimitive Object
  | (
  | [encoding:Ocsp\Asn1\Element\RawPrimitive:private] => der
  | [typeID:Ocsp\Asn1\Element\RawPrimitive:private] => 10
  | [class:Ocsp\Asn1\Element\RawPrimitive:private] => UNIVERSAL
  | [rawEncodedValue:Ocsp\Asn1\Element\RawPrimitive:private] => 
  | [tag:Ocsp\Asn1\Element\RawPrimitive:private] =>
  | )
  |  
  | )
  |  
  | [tag:Ocsp\Asn1\Element\AbstractList:private] =>
  | )
  |  
  | )
  |  
  | )
  |  
  | [2] => Array
  | (
  | [file] => C:\podatelna\_components\php7\vendor\mlocati\ocsp\src\Ocsp.php
  | [line] => 134
  | [function] => decodeOcspResponse
  | [class] => Ocsp\Ocsp
  | [type] => ->
  | [args] => Array
  | (
  | [0] => 0
  | 
  | )
  |  
  | )
  |  
  | [3] => Array
  | (
  | [file] => C:\podatelna\_devel\EmailOCSP\email_OCSP_testCustomEml.php
  | [line] => 87
  | [function] => decodeOcspResponseSingle
  | [class] => Ocsp\Ocsp
  | [type] => ->
  | [args] => Array
  | (
  | [0] => 0
  | 
  | )
  |  
  | )
  |  
  | )
  |  
  | [previous:Exception:private] =>

`

And my code is very easy I think, others certificates works fine:
`	$Ocsp = new \Ocsp\Ocsp();
	$CertificateLoader = new \Ocsp\CertificateLoader();
	$CertificateInfo = new \Ocsp\CertificateInfo();
	
	$Certificate = $CertificateLoader->fromString("-----BEGIN CERTIFICATE-----
MIIHwzCCBaugAwIBAgIEALDhPjANBgkqhkiG9w0BAQsFADB/MQswCQYDVQQGEwJD
WjEoMCYGA1UEAwwfSS5DQSBRdWFsaWZpZWQgMiBDQS9SU0EgMDIvMjAxNjEtMCsG
A1UECgwkUHJ2bsOtIGNlcnRpZmlrYcSNbsOtIGF1dG9yaXRhLCBhLnMuMRcwFQYD
VQQFEw5OVFJDWi0yNjQzOTM5NTAeFw0xOTEwMTgwODA0NDFaFw0yMDEwMTcwODA0
NDFaMFwxHzAdBgNVBAMMFkRyLiBIb3LDoWsgLSBQU0VVRE9OWU0xCzAJBgNVBAYT
AkNaMRMwEQYDVQRBDApEci4gSG9yw6FrMRcwFQYDVQQFEw5JQ0EgLSAxMDUxODk0
OTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJLjskYPvIJuLCA2GvE9
NWPpl1g52MoyYOgZD8SJBEcOvUdxlgxLtuMmaPxW/TeIc7ZI1QLVF6QDAIZ+jG9k
KwQ02okKfpgJCW4+LKdijZdbIg2SFu5Ph5HtXPbteBYwg91m8PsDl6vHKP6YTrO5
d5R3z7LjB+OQ79ww1A2OACk4usckfASRsSqmG94hZsYgOb+4l0U7bGP6LoRO2nwl
ieUuio3E/U0B6gMcUqN5A3NpJwxg2SvOqgS6qkzw21RDqHlVnEMM7qt+kqhjBvsq
ORXbvqCb+SVAf0KOHEjca7amNLIc5RO3jA8jb9yQfjjf6kf2Ro6rWVJb+fVlpXdK
LfUCAwEAAaOCA2gwggNkMDgGA1UdEQQxMC+BE3N0cmFuc2t5QGRpZ25pdGEuY3qg
GAYKKwYBBAGBuEgEBqAKDAgxMDUxODk0OTAOBgNVHQ8BAf8EBAMCBsAwCQYDVR0T
BAIwADCCASgGA1UdIASCAR8wggEbMIIBDAYNKwYBBAGBuEgKAR4BATCB+jAdBggr
BgEFBQcCARYRaHR0cDovL3d3dy5pY2EuY3owgdgGCCsGAQUFBwICMIHLGoHIVGVu
dG8ga3ZhbGlmaWtvdmFueSBjZXJ0aWZpa2F0IHBybyBlbGVrdHJvbmlja3kgcG9k
cGlzIGJ5bCB2eWRhbiB2IHNvdWxhZHUgcyBuYXJpemVuaW0gRVUgYy4gOTEwLzIw
MTQuVGhpcyBpcyBhIHF1YWxpZmllZCBjZXJ0aWZpY2F0ZSBmb3IgZWxlY3Ryb25p
YyBzaWduYXR1cmUgYWNjb3JkaW5nIHRvIFJlZ3VsYXRpb24gKEVVKSBObyA5MTAv
MjAxNC4wCQYHBACL7EABAjCBjwYDVR0fBIGHMIGEMCqgKKAmhiRodHRwOi8vcWNy
bGRwMS5pY2EuY3ovMnFjYTE2X3JzYS5jcmwwKqAooCaGJGh0dHA6Ly9xY3JsZHAy
LmljYS5jei8ycWNhMTZfcnNhLmNybDAqoCigJoYkaHR0cDovL3FjcmxkcDMuaWNh
LmN6LzJxY2ExNl9yc2EuY3JsMIGSBggrBgEFBQcBAwSBhTCBgjAIBgYEAI5GAQEw
CAYGBACORgEEMFcGBgQAjkYBBTBNMC0WJ2h0dHBzOi8vd3d3LmljYS5jei9acHJh
dnktcHJvLXV6aXZhdGVsZRMCY3MwHBYWaHR0cHM6Ly93d3cuaWNhLmN6L1BEUxMC
ZW4wEwYGBACORgEGMAkGBwQAjkYBBgEwZQYIKwYBBQUHAQEEWTBXMCoGCCsGAQUF
BzAChh5odHRwOi8vcS5pY2EuY3ovMnFjYTE2X3JzYS5jZXIwKQYIKwYBBQUHMAGG
HWh0dHA6Ly9vY3NwLmljYS5jei8ycWNhMTZfcnNhMB8GA1UdIwQYMBaAFHSCCJHj
2WRocYXW6zHkct+LJrFtMB0GA1UdDgQWBBTc33o5dlPVXLh0+YUNLu99OsdJATAT
BgNVHSUEDDAKBggrBgEFBQcDBDANBgkqhkiG9w0BAQsFAAOCAgEATbOjgEwdohCA
qyqdsG9F8X5xDDoMTqsN3D/p/OR1kDzBcFyQ4v0LmkgrPVn1oWSIxuvinLE2E/E6
iByqJNqni865wWCTt4kZtWCQlQwqPlUG+bvCjY3PlouU+Z0qVKebZ9vtAQNXyp1e
CH1Zjd0ik724KvAWU8ZvaCReDQO7ACLuyZpJnF/xL1cmS+bRkXUw50Hn2YvEHit6
aiPTDFoMWAFGSUQnKm/eksc+e/i7tg5mpRCc2aFAlDcTsLfpeuayBkzEijYKzSUp
5zMitBH5hG/uOQZO1SjxJnzHIyIiXsqO+1wercXYM9bYcDRkw+L7CtSiUlC1OtRa
1yKN7y7F5XJd29MJgfu5DgQ4RAIFcGwItUVc2HBjpmNxdu9Xf5wC12zRkGeEnsPD
FKPpbHUjBZZYNs2nbtYqyk4jo2ORhb3KqXpIpDtl5Ok7oeLMBY650DHxiCDNBgpt
1QaVbS31g/ZycpA0w5ELmdtBdAsOdgmvdMexKFPzvt/MBrXxu2BsdPA0CGWMOq3K
TZEsESf+G4FDLzzFNz5DbCRBP55sR2G+hvvXhPU2BPYI9Ir3vgnE9w/Fxxqp6xGG
GIKlRALSletgwQod8ktwZEhfyO8OqFt6opMN8qSMHv0HRHvlYyz/3kq83/lXklT6
OBgnA/Xji2TzgGS+7477ep2pycy3wmI=
-----END CERTIFICATE-----
");
	$OcspResponderUrl = $CertificateInfo->extractOcspResponderUrl($Certificate);
	
	var_dump($CertificateInfo->extractIssuerCertificateUrl($Certificate));
	$IssuerCertificate = $CertificateLoader->fromString(file_get_contents($CertificateInfo->extractIssuerCertificateUrl($Certificate)));

	var_dump($OcspResponderUrl);
	
	$RequestInfo = $CertificateInfo->extractRequestInfo($Certificate, $IssuerCertificate);
	var_dump($RequestInfo);
	$RequestBody = $Ocsp->buildOcspRequestBodySingle($RequestInfo);
	
	$hCurl = curl_init();
	curl_setopt($hCurl, CURLOPT_URL, $OcspResponderUrl);
	curl_setopt($hCurl, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($hCurl, CURLOPT_POST, true);
	curl_setopt($hCurl, CURLOPT_HTTPHEADER, ['Content-Type: ' . \Ocsp\Ocsp::OCSP_REQUEST_MEDIATYPE]);
	curl_setopt($hCurl, CURLOPT_SAFE_UPLOAD, true);
	curl_setopt($hCurl, CURLOPT_POSTFIELDS, $RequestBody);
	$result = curl_exec($hCurl);
	var_dump($result);
	$info = curl_getinfo($hCurl);
	
	if ($info['http_code'] !== 200) {
	    echo "OCSP: Whoops, here we'd expect a 200 HTTP code";
	}
	if ($info['content_type'] !== \Ocsp\Ocsp::OCSP_RESPONSE_MEDIATYPE) {
	    echo "OCSP: Whoops, the Content-Type header of the response seems wrong!";
	}
	
	$Response = $Ocsp->decodeOcspResponseSingle($result);
	var_dump($Response);`

Any help will be very fine.

Thank you.

**Comment by JiriSch** [comment]
It works now, some issue with their OCSP server.

Thank you.
