### ISSUE TITLE
Nonce extension

### ISSUE THREAD

**Issue by flaviencrochard** [mlocati/ocsp#7]
Hello,
While using this wondeful package, i encountered this exception :
CouldNotCheckCertificate-error-Cannot build OCSP Response 'Request unauthorized
After checking, this is about the nonce extention added in the RFC 8954 (https://datatracker.ietf.org/doc/rfc8954/)
The original RFC has been updated according to that modification (https://datatracker.ietf.org/doc/html/rfc6960#section-4.4.1)
Could it be added in the function buildOcspRequestBody located in the Ocsp class ?
Thanks in advance :)

**Comment by mlocati** [comment]
> CouldNotCheckCertificate-error-Cannot build OCSP Response 'Request unauthorized

Do you know a CA that uses/requires nonces?

**Comment by flaviencrochard** [comment]
Apparently, this issue can be closed : i don't reproduce anymore the exception.

The CA used is "USERTrust RSA Certification Authority"
